apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
      {{- include "mustgatherapiserver.selectorLabels" . | nindent 6 }}
  name: must-gather-server
spec:
  port:
    targetPort: serv-port
  tls:
    termination: edge
  to:
    kind: ""
    name: must-gather-server
    weight: null
