# permissions for end users to view mustgatherapiservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mustgatherapiserver-viewer-role
rules:
- apiGroups:
  - mustgatherserver.michael-washer.com
  resources:
  - mustgatherapiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mustgatherserver.michael-washer.com
  resources:
  - mustgatherapiservers/status
  verbs:
  - get
